name: Playwright BDD CI

on:
  push:
    branches: [main]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Install Playwright Browsers
        run: mvn exec:java "-Dexec.mainClass=com.microsoft.playwright.CLI" "-Dexec.args=install"

      - name: Run Tests
        run: mvn clean test -Dbrowser=chromium -Dheadless=true